#! /bin/sh

#### AUTOSTART ####
pgrep -x sxhkd > /dev/null || sxhkd &
$HOME/.config/polybar/launch.sh &
eww daemon &
eww open center-bar &

# Apply cursor outside windows
xsetroot -cursor_name left_ptr

#### EWW ####
# bspc config ignore_ewmh_struts true

#### MONITORS ####
bspc monitor DP-0 -d 1 2 3 4 5 6
bspc monitor DP-4 -d 1 2 3 4 5 6
bspc monitor DP-2 -d 1 2 3 4 5 6

#### BSPWM CONFIG ####
bspc config border_width         2
bspc config window_gap           9
bspc config top_padding          40
bspc config bottom_padding       0
bspc config left_padding         -2
bspc config right_padding        -2

bspc config single_monocle       false
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer         false
bspc config pointer_follows_focus false
bspc config pointer_follows_monitor false
bspc config swallow_first_click false
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

#### BSPWM coloring ####
bspc config normal_border_color		      "#FF4894"
bspc config active_border_color	        "#22FFFF"
bspc config focused_border_color	      "#C1FF3C"
bspc config presel_feedback_color	      "#C1FF3C"
bspc config urgent_border_color 	      "#DD2727"
