import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[font]
size = 13.5
builtin_box_drawing = true

[font.bold]
family = "FiraCode Nerd Font"
# family = "Ubuntu Mono"
# family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.normal]
family = "FiraCode Nerd Font"
# family = "Ubuntu Mono"
# family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 16

[font.glyph_offset]
x = 0
y = 8

[mouse]
hide_when_typing = true

[shell]
args = ["-l", "-c", "tmux"]
program = "/bin/zsh"

[window]
dynamic_padding = true
opacity = 0.93
startup_mode = "Maximized"

[window.padding]
x = 0
y = 0
